name: github pages

on:
  push:
    branches:
      - main  # Set a branch that will trigger a deployment
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
          
      - name: Install dependencies
        run: |
          npm install postcss -D
          npm install -g postcss-cli
          npm install -g autoprefixer

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          # extended: true

      - name: Build
        working-directory: ./Project-Showcase
        run: hugo --minify
        
      - name: Create CNAME file
        run: echo project-showcase.che-ict.nl > ./Project-Showcase/public/CNAME

      - name: Set Access Token in addProject.js
        run: sed -i "s|const accessToken = \"\";|const accessToken = \"${{ secrets.ACCESS_TOKEN }}\";|" ./Project-Showcase/static/js/addProject.js

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./Project-Showcase/public
