name: github pages

on:
  push:
    branches:
      - main  # Set a branch that will trigger a deployment
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Install dependencies
        run: |
          npm install postcss -D
          npm install -g postcss-cli
          npm install -g autoprefixer

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          # extended: true

      - name: Build
        working-directory: ./Project-Showcase
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./Project-Showcase/public

      - name: Setup Serverless Function
        run: |
          npm install axios
          mkdir -p .github/workflows/serverless
          echo 'name: serverless\n\non:\n  push:\n    branches:\n      - main\n\njobs:\n  deploy:\n    runs-on: ubuntu-22.04\n    steps:\n      - uses: actions/checkout@v3\n        with:\n          submodules: true\n          fetch-depth: 0\n\n      - name: Setup Node.js\n        uses: actions/setup-node@v2\n        with:\n          node-version: 14\n\n      - name: Install Dependencies\n        run: npm install\n\n      - name: Handle API Requests\n        run: npm start' > .github/workflows/serverless/serverless.yml
        working-directory: ./Project-Showcase

      - name: Commit and Push Serverless Function
        run: |
          git config --global user.name "MaikeyR"
          git config --global user.email "maikel.reijneke@gmail.com"
          git add .
          git commit -m "Add serverless function"
          git push

      - name: Deploy Serverless Function
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .github/workflows/serverless
